---
- name: get pip
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/opt/get-pip.py"
    validate_certs: "no"
  register: get_pip
  until: get_pip|success
  retries: 3
  delay: 2

- name: install pip with get-pip.py
  shell: "python /opt/get-pip.py"
  changed_when: false
  register: pip_install
  until: pip_install|success
  retries: 3
  delay: 2
