---
- name: get latest gerrit-projects
  git:
    repo: '{{ gerrit_projects_repo_url }}'
    dest: "{{ gerrit_projects_state_path }}/projects"
    version: master
  register: projects_repo
- name: setup projects.ini
  template:
    src: projects.ini.j2
    dest: "{{ gerrit_projects_state_path }}/projects.ini"
    owner: root
    group: root
- name: update gerrit-projects
  shell: |
    GERRIT_CONFIG={{ gerrit_config_path }} \
    GERRIT_SECURE_CONFIG={{ gerrit_secure_config_path }} \
    PROJECTS_INI={{ gerrit_projects_state_path }}/projects.ini \
    PROJECTS_YAML={{ gerrit_projects_state_path }}/projects/projects.yaml \
    manage-projects -d >> /var/log/manage_projects.log 2>&1
  when: projects_repo.changed or gerrit_projects_always_manage_projects
